const minerals = [
  // ── CRYSTALS ───────────────────────────────────────────────────────────────
  {
    name: 'Quartz',
    category: 'Crystals',
    subCategory: 'Silicate',
    hardness: 7,
    rarity: 'Common',
    description: 'Quartz is the most abundant mineral in the Earth\'s continental crust. It is a silicate mineral with a hardness of 7 on the Mohs scale, making it highly resistant to weathering.',
    origin: 'Worldwide',
    uses: ['Electronics', 'Jewelry', 'Glassmaking', 'Abrasives'],
    image: 'https://images.unsplash.com/photo-1596541223130-5d31a73fb6c6?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: true,
    featured: true,
    chemicalFormula: 'SiO2',
    crystalSystem: 'Trigonal',
    luster: 'Vitreous',
    color: ['Clear', 'White', 'Gray', 'Purple', 'Pink'],
  },
  {
    name: 'Amethyst',
    category: 'Crystals',
    subCategory: 'Quartz variety',
    hardness: 7,
    rarity: 'Uncommon',
    description: 'Amethyst is a violet variety of quartz often used in jewelry. Its beautiful purple color is due to irradiation, iron impurities, and trace elements.',
    origin: 'Brazil, Uruguay, Zambia',
    uses: ['Jewelry', 'Meditation', 'Decoration', 'Collectibles'],
    image: 'https://images.unsplash.com/photo-1523467117515-94637d79465a?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: true,
    featured: true,
    chemicalFormula: 'SiO2',
    crystalSystem: 'Trigonal',
    luster: 'Vitreous',
    color: ['Purple', 'Violet'],
  },
  {
    name: 'Rose Quartz',
    category: 'Crystals',
    subCategory: 'Quartz variety',
    hardness: 7,
    rarity: 'Common',
    description: 'Rose quartz is a pink-colored quartz crystal known as the stone of love. Its soft pink hue comes from trace amounts of titanium, iron, or manganese.',
    origin: 'Brazil, Madagascar, South Africa',
    uses: ['Jewelry', 'Meditation', 'Decoration'],
    image: 'https://images.unsplash.com/photo-1615190284325-964fd379714c?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: false,
    featured: false,
    chemicalFormula: 'SiO2',
    crystalSystem: 'Trigonal',
    luster: 'Vitreous to Waxy',
    color: ['Pink', 'Rose'],
  },
  {
    name: 'Citrine',
    category: 'Crystals',
    subCategory: 'Quartz variety',
    hardness: 7,
    rarity: 'Uncommon',
    description: 'Citrine is a yellow to orange variety of quartz, named from the French word for lemon. It is one of the most popular gemstones used in jewelry.',
    origin: 'Brazil, Bolivia, Spain',
    uses: ['Jewelry', 'Decoration', 'Collectibles'],
    image: 'https://images.unsplash.com/photo-1614035030394-b6e5b01e0737?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: false,
    featured: false,
    chemicalFormula: 'SiO2',
    crystalSystem: 'Trigonal',
    luster: 'Vitreous',
    color: ['Yellow', 'Orange', 'Brown'],
  },

  // ── GEMSTONES ───────────────────────────────────────────────────────────────
  {
    name: 'Ruby',
    category: 'Gemstones',
    subCategory: 'Corundum',
    hardness: 9,
    rarity: 'Rare',
    description: 'Ruby is a pink to blood-red colored gemstone, a variety of the mineral corundum. It is one of the most valuable precious stones.',
    origin: 'Myanmar, Thailand, Sri Lanka',
    uses: ['Jewelry', 'Watches', 'Laser technology', 'Collectibles'],
    image: 'https://images.unsplash.com/photo-1596542103282-3d5f3017a232?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: true,
    featured: true,
    chemicalFormula: 'Al2O3',
    crystalSystem: 'Trigonal',
    luster: 'Adamantine to Vitreous',
    color: ['Red', 'Deep Red', 'Pink-Red'],
  },
  {
    name: 'Sapphire',
    category: 'Gemstones',
    subCategory: 'Corundum',
    hardness: 9,
    rarity: 'Rare',
    description: 'Sapphire is a precious gemstone, a variety of corundum. While blue is most typical, sapphires can be almost any color.',
    origin: 'Sri Lanka, Kashmir, Myanmar',
    uses: ['Jewelry', 'Watch crystals', 'Scientific instruments'],
    image: 'https://images.unsplash.com/photo-1605732163013-066a50da8093?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: true,
    featured: false,
    chemicalFormula: 'Al2O3',
    crystalSystem: 'Trigonal',
    luster: 'Vitreous to Adamantine',
    color: ['Blue', 'Yellow', 'Green', 'Pink', 'White'],
  },
  {
    name: 'Emerald',
    category: 'Gemstones',
    subCategory: 'Beryl',
    hardness: 7.5,
    rarity: 'Very Rare',
    description: 'Emerald is a variety of the mineral beryl colored green by trace amounts of chromium and vanadium.',
    origin: 'Colombia, Brazil, Zambia',
    uses: ['Jewelry', 'Collectibles', 'Investment'],
    image: 'https://images.unsplash.com/photo-1596542103387-ec6d81206f6e?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: true,
    featured: true,
    chemicalFormula: 'Be3Al2(SiO3)6',
    crystalSystem: 'Hexagonal',
    luster: 'Vitreous',
    color: ['Green', 'Deep Green'],
  },
  {
    name: 'Diamond',
    category: 'Gemstones',
    subCategory: 'Native Element',
    hardness: 10,
    rarity: 'Legendary',
    description: 'Diamond is the hardest known natural material, scoring 10 on the Mohs scale. It is prized for its brilliance and durability.',
    origin: 'South Africa, Russia, Botswana',
    uses: ['Jewelry', 'Cutting tools', 'Abrasives', 'Electronics'],
    image: 'https://images.unsplash.com/photo-1596542103350-256d0d29d89d?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: true,
    featured: true,
    chemicalFormula: 'C',
    crystalSystem: 'Cubic',
    luster: 'Adamantine',
    color: ['Clear', 'Yellow', 'Blue', 'Pink', 'Black'],
  },

  // ── MINERALS ────────────────────────────────────────────────────────────────
  {
    name: 'Pyrite',
    category: 'Minerals',
    subCategory: 'Sulfide',
    hardness: 6.5,
    rarity: 'Common',
    description: 'Pyrite, also known as Fool\'s Gold, is an iron sulfide mineral known for its pale brass-yellow hue and metallic luster.',
    origin: 'Spain, Peru, USA',
    uses: ['Sulfuric acid production', 'Jewelry', 'Collectibles'],
    image: 'https://images.unsplash.com/photo-1596542103131-0da5d3c8c764?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: true,
    featured: false,
    chemicalFormula: 'FeS2',
    crystalSystem: 'Cubic',
    luster: 'Metallic',
    color: ['Brass-yellow', 'Gold'],
  },
  {
    name: 'Malachite',
    category: 'Minerals',
    subCategory: 'Carbonate',
    hardness: 3.5,
    rarity: 'Uncommon',
    description: 'Malachite is a copper carbonate hydroxide mineral with a vivid green color and distinctive banded patterns.',
    origin: 'Congo, Russia, Australia',
    uses: ['Jewelry', 'Decoration', 'Pigment', 'Collectibles'],
    image: 'https://images.unsplash.com/photo-1620311244431-7221087e600f?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: false,
    featured: false,
    chemicalFormula: 'Cu2(CO3)(OH)2',
    crystalSystem: 'Monoclinic',
    luster: 'Vitreous to Silky',
    color: ['Green', 'Banded Green'],
  },
  {
    name: 'Obsidian',
    category: 'Minerals',
    subCategory: 'Volcanic Glass',
    hardness: 5,
    rarity: 'Common',
    description: 'Obsidian is a naturally occurring volcanic glass formed by rapidly cooling lava. It was widely used by ancient civilizations for cutting tools.',
    origin: 'USA, Mexico, Iceland',
    uses: ['Tools', 'Jewelry', 'Collectibles', 'Surgery blades'],
    image: 'https://images.unsplash.com/photo-1596542103323-93dfd7719601?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: false,
    featured: false,
    chemicalFormula: 'SiO2',
    crystalSystem: 'Amorphous',
    luster: 'Vitreous',
    color: ['Black', 'Dark Brown', 'Green'],
  },
  {
    name: 'Fluorite',
    category: 'Minerals',
    subCategory: 'Halide',
    hardness: 4,
    rarity: 'Common',
    description: 'Fluorite is often called the most colorful mineral in the world, with hues including purple, blue, green, yellow, and pink.',
    origin: 'China, Mexico, South Africa',
    uses: ['Optics', 'Fluorine production', 'Steel industry', 'Collectibles'],
    image: 'https://images.unsplash.com/photo-1596542103176-7977461972f0?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: false,
    featured: false,
    chemicalFormula: 'CaF2',
    crystalSystem: 'Cubic',
    luster: 'Vitreous',
    color: ['Purple', 'Blue', 'Green', 'Yellow', 'Pink', 'Clear'],
  },
  {
    name: 'Turquoise',
    category: 'Minerals',
    subCategory: 'Phosphate',
    hardness: 5,
    rarity: 'Rare',
    description: 'Turquoise is an opaque, blue-to-green mineral prized as a gemstone for thousands of years.',
    origin: 'Iran, USA, China',
    uses: ['Jewelry', 'Decoration', 'Collectibles'],
    image: 'https://images.unsplash.com/photo-1615190284451-97816668798e?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: false,
    featured: true,
    chemicalFormula: 'CuAl6(PO4)4(OH)8',
    crystalSystem: 'Triclinic',
    luster: 'Waxy to Subvitreous',
    color: ['Blue', 'Green-Blue', 'Turquoise'],
  },

  // ── IGNEOUS ─────────────────────────────────────────────────────────────────
  {
    name: 'Granite',
    category: 'Igneous',
    subCategory: 'Intrusive',
    hardness: 6.5,
    rarity: 'Common',
    description: 'Granite is a coarse-grained intrusive igneous rock composed primarily of quartz, feldspar, and mica.',
    origin: 'Worldwide',
    uses: ['Construction', 'Countertops', 'Monuments', 'Paving'],
    image: 'https://images.unsplash.com/photo-1596541222712-4c284752c0e8?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: false,
    featured: false,
    chemicalFormula: 'SiO2, Al2O3, K2O',
    crystalSystem: 'N/A (Rock)',
    luster: 'Dull to Vitreous',
    color: ['Gray', 'Pink', 'White', 'Black'],
  },
  {
    name: 'Basalt',
    category: 'Igneous',
    subCategory: 'Extrusive',
    hardness: 6,
    rarity: 'Common',
    description: 'Basalt is a fine-grained extrusive igneous rock formed from the rapid cooling of lava. It is the most common rock type in oceanic crust.',
    origin: 'Hawaii, Iceland, India',
    uses: ['Construction', 'Road paving', 'Fiber reinforcement'],
    image: 'https://images.unsplash.com/photo-1596542103215-6a568b2be8e2?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: false,
    featured: false,
    chemicalFormula: 'SiO2, MgO, FeO, CaO',
    crystalSystem: 'N/A (Rock)',
    luster: 'Dull',
    color: ['Black', 'Dark Gray'],
  },

  // ── SEDIMENTARY ─────────────────────────────────────────────────────────────
  {
    name: 'Limestone',
    category: 'Sedimentary',
    subCategory: 'Carbonate',
    hardness: 3,
    rarity: 'Common',
    description: 'Limestone is a carbonate sedimentary rock composed mainly of calcite. Many important fossils are found in limestone.',
    origin: 'Worldwide',
    uses: ['Construction', 'Cement', 'Agriculture', 'Glass'],
    image: 'https://images.unsplash.com/photo-1596542103328-9844f2ef6849?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: false,
    featured: false,
    chemicalFormula: 'CaCO3',
    crystalSystem: 'N/A (Rock)',
    luster: 'Dull',
    color: ['White', 'Gray', 'Cream', 'Tan'],
  },
  {
    name: 'Sandstone',
    category: 'Sedimentary',
    subCategory: 'Clastic',
    hardness: 6,
    rarity: 'Common',
    description: 'Sandstone is a clastic sedimentary rock composed mainly of sand-sized grains of mineral or rock material.',
    origin: 'Worldwide',
    uses: ['Construction', 'Paving', 'Filtration', 'Glassmaking'],
    image: 'https://images.unsplash.com/photo-1596542103323-93dfd7719601?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: false,
    featured: false,
    chemicalFormula: 'SiO2',
    crystalSystem: 'N/A (Rock)',
    luster: 'Dull to Granular',
    color: ['Tan', 'Red', 'Brown', 'Yellow'],
  },
  {
    name: 'Shale',
    category: 'Sedimentary',
    subCategory: 'Clastic',
    hardness: 2,
    rarity: 'Common',
    description: 'Shale is a fine-grained, clastic sedimentary rock composed of mud. It is the most common sedimentary rock.',
    origin: 'Worldwide',
    uses: ['Brick making', 'Cement', 'Pottery', 'Natural gas source'],
    image: 'https://images.unsplash.com/photo-1596541222850-80e1811a7f05?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: false,
    featured: false,
    chemicalFormula: 'Al2Si2O5(OH)4',
    crystalSystem: 'N/A (Rock)',
    luster: 'Dull',
    color: ['Gray', 'Black', 'Brown', 'Green'],
  },

  // ── METAMORPHIC ─────────────────────────────────────────────────────────────
  {
    name: 'Marble',
    category: 'Metamorphic',
    subCategory: 'Carbonate',
    hardness: 3,
    rarity: 'Common',
    description: 'Marble is a metamorphic rock composed of recrystallized carbonate minerals. It has been prized for sculpture and architecture throughout history.',
    origin: 'Italy, Greece, India',
    uses: ['Sculpture', 'Architecture', 'Flooring', 'Countertops'],
    image: 'https://images.unsplash.com/photo-1596541223350-256d0d29d89d?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: false,
    featured: false,
    chemicalFormula: 'CaCO3',
    crystalSystem: 'N/A (Rock)',
    luster: 'Waxy to Vitreous',
    color: ['White', 'Gray', 'Pink', 'Green', 'Black'],
  },
  {
    name: 'Slate',
    category: 'Metamorphic',
    subCategory: 'Foliated',
    hardness: 3.5,
    rarity: 'Common',
    description: 'Slate is a fine-grained metamorphic rock from the metamorphism of shale. It splits into smooth, flat pieces.',
    origin: 'Wales, USA, Brazil',
    uses: ['Roofing', 'Flooring', 'Blackboards', 'Pool tables'],
    image: 'https://images.unsplash.com/photo-1596541223250-b088dfd72c4c?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: false,
    featured: false,
    chemicalFormula: 'SiO2, Al2O3',
    crystalSystem: 'N/A (Rock)',
    luster: 'Waxy to Pearly',
    color: ['Gray', 'Black', 'Green', 'Purple'],
  },
  {
    name: 'Quartzite',
    category: 'Metamorphic',
    subCategory: 'Non-Foliated',
    hardness: 7,
    rarity: 'Common',
    description: 'Quartzite is a hard, non-foliated metamorphic rock formed from sandstone. Its high durability makes it ideal for construction.',
    origin: 'Worldwide',
    uses: ['Construction', 'Railroad ballast', 'Flooring', 'Worktops'],
    image: 'https://images.unsplash.com/photo-1615190284350-b0b8dfd72c4c?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: false,
    featured: false,
    chemicalFormula: 'SiO2',
    crystalSystem: 'N/A (Rock)',
    luster: 'Vitreous to Granular',
    color: ['White', 'Gray', 'Pink', 'Red'],
  },
  {
    name: 'Lapis Lazuli',
    category: 'Metamorphic',
    subCategory: 'Contact Metamorphic',
    hardness: 5,
    rarity: 'Rare',
    description: 'Lapis lazuli is a deep-blue metamorphic rock prized since antiquity. It was used as a pigment by Renaissance painters.',
    origin: 'Afghanistan, Chile, Russia',
    uses: ['Jewelry', 'Pigment', 'Decoration', 'Collectibles'],
    image: 'https://images.unsplash.com/photo-1517496010041-0da5f3c8c764?auto=format&fit=crop&w=800&q=80',
    gallery: [],
    trending: true,
    featured: true,
    chemicalFormula: '(Na,Ca)8Al6Si6O24(S,SO4)',
    crystalSystem: 'Cubic',
    luster: 'Waxy to Greasy',
    color: ['Deep Blue', 'Blue-Violet'],
  },
];

module.exports = minerals;
